[colors]
transparent_background_colors = false

[colors.bright]
black = "#626880"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
# orange = "#f2d5cf"
red = "#e78284"
white = "#a5adce"
yellow = "#e5c890"

[colors.normal]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
# orange = "#ef9f76"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[colors.primary]
background = "#eff1f5"
bright_foreground = "#d5c4a1"
dim_foreground = "#3c3836"
foreground = "#4c4f69"
