[colors]
transparent_background_colors = false

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fe8019"
yellow = "#fabd2f"

[colors.normal]
black = "#7c6f64"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#d79921"

[colors.primary]
background = "#282828"
bright_foreground = "#d5c4a1"
dim_foreground = "#3c3836"
foreground = "#ebdbb2"
